name: ling573-2022-spring
channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - ipykernel
  - tqdm
  - pandas
  - pip>=22.0
  - pytorch
  - pytorch-lightning>=1.6.1
  - pip:
      - transformers>=4.18.0

