name: ling573-2022-spring
channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - ipykernel
  - numpy==1.21.5
  - tqdm
  - pandas==1.3.5
  - sklearn-pandas
  - scikit-learn==0.24.2
  - lightgbm==3.2.1
  - pip>=22.0
  - pytorch==1.10.0
  - pytorch-lightning>=1.6.1
  - pip:
      - transformers>=4.18.0
      - emoji==0.6.0
      - nltk==3.2.5
